### ISSUE TITLE
Apply rice

### ISSUE THREAD

**Issue by 3dgoose** [husseinhareb/dotfiles--Awesome-#1]
Admitting I have copied those files to ~/.config , what I am supposed to do to have a background and make my desktop look exactly like yours ? Download packages ?

**Comment by husseinhareb** [comment]
- You are supposed to have the packages associated with these configs:
`polybar cava neovim rofi kitty dunst awesome neofetch` and [picom-pijulius](https://github.com/pijulius/picom).

- You are also supposed to copy the config folders to your `~/.config/` and the Scripts folder to your home directory `~/`
- If the icons didn't load try installing [Symbols Nerd Fonts](https://www.nerdfonts.com/font-downloads).
- Don't forget to make the bash files executable by using `chmod +x /path/to/file`.
- I recommend  to check newer rices done by me which i think they look cooler :) [qtile-1](https://github.com/husseinhareb/qtile-config) and [qtile-2](https://github.com/husseinhareb/my-dotfiles).
